draw_config:
  dark_mode: true
  n_columns: 1
  draw_key_sides: true
  separate_combo_diagrams: true
  combo_diagrams_scale: 2
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 40.0
  combo_h: 40.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  footer_text: "luftmensch-luftmensch/sofle"
  svg_extra_style: "svg.keymap { font-family: 'Sarasa Mono Slab SC'; }"
  small_pad: 2.0
  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    "&mmv MOVE_DOWN":
      t: "$$mdi:menu-down$$"
      s: "$$mdi:mouse$$"
    "&mmv MOVE_UP":
      t: "$$mdi:menu-up$$"
      s: "$$mdi:mouse$$"
    "&mmv MOVE_LEFT":
      t: "$$mdi:menu-left$$"
      s: "$$mdi:mouse$$"
    "&mmv MOVE_RIGHT":
      t: "$$mdi:menu-right$$"
      s: "$$mdi:mouse$$"
    "&mkp LCLK": "$$mdi:mouse-left-click-outline$$"
    "&mkp MCLK": "$$mdi:mouse-scroll-wheel$$"
    "&mkp RCLK": "$$mdi:mouse-right-click-outline$$"
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
    "&tilde": "$$mdi:tilde$$"
    "&hash": "$$mdi:pound$$"
    "&at": "$$mdi:at$$"
    "&bktk": "`"
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: "$$mdi:transfer$$"
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: true
  zmk_remove_keycode_prefix: ["IT_"]

  zmk_keycode_map:
    LESS: "<"
    GREAT: ">"
    EACU: "è"
    AST: "*"
    MUTE: "$$mdi:volume-off$$"
    C_MUTE: "$$mdi:volume-off$$"
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: "^"
    MINUS: "-"
    UNDERSCORE: _
    UNDER: "?"
    SLASH: /
    FSLH: /
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: \
    BSLH: \
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ;
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
    ESC: "$$mdi:keyboard-esc$$"
    UP: "$$mdi:arrow-up-bold$$"
    DOWN: "$$mdi:arrow-down-bold$$"
    LEFT: "$$mdi:arrow-left-bold$$"
    RIGHT: "$$mdi:arrow-right-bold$$"
    BACKSPACE: "$$mdi:backspace$$"
    DELETE: "$$mdi:backspace-reverse-outline$$"
    TAB: "$$mdi:keyboard-tab$$"
    CAPS: "$$mdi:apple-keyboard-caps$$"
    LSHFT: "$$mdi:apple-keyboard-shift$$"
    RSHIFT: "$$mdi:apple-keyboard-shift$$"
    LCTRL: "$$mdi:apple-keyboard-control$$"
    LGUI: "$$mdi:apple-keyboard-command$$"
    LALT: "$$mdi:apple-keyboard-option$$"
    RCTRL: "$$mdi:apple-keyboard-control$$"
    RALT: "$$mdi:apple-keyboard-option$$"
    RIGHT_ALT: "$$mdi:apple-keyboard-option$$"
    ENTER: "$$mdi:keyboard-return$$"
    SPACE: "$$mdi:keyboard-space$$"

  zmk_combos: {}
  zmk_preamble: "#define KEYMAP_DRAWER"
  zmk_additional_includes: []
